### ISSUE TITLE
Issues installing NuGet package on Mono

### ISSUE THREAD

**Issue by AndrewSaninCreuna** [whyleee/generator-aspnet-powermvc#2]
Installation of the package fails with the NullReference exception when it's installed on Mono (Mac). 

It seams that the problem is caused by https://github.com/whyleee/nogit package that uses PowerShell scripts.

Besides that the package depends on the Windows version of Node.js and adds windows CMD files to the project.

**Comment by whyleee** [comment]
Use a newer (0.5) version from npm. NuGet packages are outdated and they doesn't support Mac/Mono.
